const seasonalPalettes = {
  'autumn-warm': {
    label: 'Autumn Warm',
    description: 'Tông ấm vàng đất, màu hổ phách và xanh ô liu đặc trưng mùa thu ấm.',
    undertone: 'warm',
    palette: ['#C8861A', '#8B5A2B', '#6B7C2E', '#C4602A', '#F5E6C8', '#B5651D'],
    avoid: ['#B0C4DE', '#C0C0C0', '#E8F4FF'],
    metallic: 'gold',
    outfitKeywords: {
      casual: ['áo len đất nâu', 'quần ô liu', 'giày camel'],
      office: ['blazer nâu vàng', 'quần kem', 'áo sơ mi ivory'],
      party: ['váy đồng màu', 'trang sức vàng', 'clutch da bò'],
    },
  },
  'autumn-deep': {
    label: 'Autumn Deep',
    description: 'Tông tối sâu ấm như rượu vang đỏ, xanh rừng và nâu socola.',
    undertone: 'warm',
    palette: ['#8B0000', '#2F4F2F', '#4A2C2A', '#1F3A3A', '#483D8B', '#1C1008'],
    avoid: ['#E0E8FF', '#FFB6C1', '#F0FFFE'],
    metallic: 'gold',
    outfitKeywords: {
      casual: ['áo len tối màu', 'quần da nâu', 'boots đen'],
      office: ['suit xanh rừng', 'áo đen cổ cao', 'quần nâu đen'],
      party: ['váy vải nhung tối', 'trang sức vàng antique', 'túi da thật'],
    },
  },
  'autumn-rich': {
    label: 'Autumn Rich',
    description: 'Tông đất đậm bão hòa như gạch, đồng và xanh mòng két sâu.',
    undertone: 'warm',
    palette: ['#B5451B', '#CC8800', '#1A5C5C', '#A0360A', '#C49A3C', '#B87333'],
    avoid: ['#E8F0FF', '#FFC0CB', '#F0E8FF'],
    metallic: 'gold',
    outfitKeywords: {
      casual: ['áo màu gạch', 'quần mòng két', 'túi da đồng'],
      office: ['blazer đồng', 'áo teal đậm', 'quần đen'],
      party: ['đầm màu đồng', 'vòng vàng gold', 'sandal ánh kim vàng'],
    },
  },
  'autumn-muted': {
    label: 'Autumn Muted',
    description: 'Tông ấm nhạt dịu như hồng bụi, sage xanh và terracotta mờ.',
    undertone: 'warm',
    palette: ['#C4A0A0', '#8A9E70', '#C08060', '#BEA898', '#6A9898', '#8A8A5E'],
    avoid: ['#FF0080', '#00FFFF', '#F0F0FF'],
    metallic: 'gold',
    outfitKeywords: {
      casual: ['áo hồng nude', 'quần sage', 'giày taupe'],
      office: ['vest màu tro ấm', 'blouse dusty rose', 'quần greige'],
      party: ['đầm dusty rose', 'trang sức vàng nhạt', 'túi beige'],
    },
  },

  'winter-cool': {
    label: 'Winter Cool',
    description: 'Tương phản cao, lạnh rõ nét — trắng tinh, đen tuyệt đối và đỏ lạnh.',
    undertone: 'cool',
    palette: ['#FFFFFF', '#000000', '#1A237E', '#C41E3A', '#00695C', '#283593'],
    avoid: ['#D2691E', '#FFA500', '#9ACD32'],
    metallic: 'silver',
    outfitKeywords: {
      casual: ['áo trắng tinh', 'quần đen', 'giày đế trắng'],
      office: ['suit đen', 'blouse trắng', 'phụ kiện bạc'],
      party: ['váy đỏ lạnh', 'trang sức bạc', 'túi đen ánh kim'],
    },
  },
  'winter-dark': {
    label: 'Winter Dark',
    description: 'Màu sắc lạnh tối sâu như midnight navy, mận tím và than chì.',
    undertone: 'cool',
    palette: ['#4A0080', '#0D1B4B', '#2C2C2C', '#1B4320', '#000000', '#6B0020'],
    avoid: ['#FFD700', '#FFA07A', '#FFA500'],
    metallic: 'silver',
    outfitKeywords: {
      casual: ['áo hoodie than', 'quần navy', 'boots đen'],
      office: ['suit charcoal', 'áo cổ lọ đen', 'quần midnight navy'],
      party: ['váy nhung tím', 'trang sức bạc ánh', 'túi da đen'],
    },
  },
  'winter-bright': {
    label: 'Winter Bright',
    description: 'Màu lạnh sặc sỡ bão hòa như magenta, cobalt và xanh electric.',
    undertone: 'cool',
    palette: ['#FF1493', '#0047AB', '#8A00FF', '#FF69B4', '#0077FF', '#00A86B'],
    avoid: ['#C4A882', '#DEB887', '#F5DEB3'],
    metallic: 'silver',
    outfitKeywords: {
      casual: ['áo cobalt blue', 'quần đen', 'sneaker trắng'],
      office: ['blazer cobalt', 'áo trắng', 'quần xám lạnh'],
      party: ['váy magenta', 'trang sức ánh kim bạc', 'clutch ánh tím'],
    },
  },
  'winter-clear': {
    label: 'Winter Clear',
    description: 'Màu lạnh trong vắt, tươi sáng như trắng tinh, aqua và vàng chanh.',
    undertone: 'cool',
    palette: ['#FFFFFF', '#000000', '#FF6B6B', '#87CEEB', '#00FF7F', '#FFF44F'],
    avoid: ['#D2B48C', '#BC8F5F', '#A0826D'],
    metallic: 'silver',
    outfitKeywords: {
      casual: ['áo trắng sáng', 'quần xanh dương nhạt', 'giày trắng'],
      office: ['blouse trắng tinh', 'quần kem lạnh', 'phụ kiện chrome'],
      party: ['váy aqua', 'trang sức bạc bóng', 'túi ánh kim trắng'],
    },
  },

  'spring-warm': {
    label: 'Spring Warm',
    description: 'Ấm áp tươi sáng như đào, san hô và vàng nắng mùa xuân.',
    undertone: 'warm',
    palette: ['#FFDAB9', '#FF7F50', '#FFD700', '#90EE90', '#40E0D0', '#FFFFF0'],
    avoid: ['#2F4F4F', '#000033', '#36454F'],
    metallic: 'gold',
    outfitKeywords: {
      casual: ['áo coral', 'quần trắng kem', 'giày vàng'],
      office: ['blazer vàng mật ong', 'blouse đào', 'quần kem ấm'],
      party: ['váy san hô', 'trang sức vàng sáng', 'túi ánh vàng nhẹ'],
    },
  },
  'spring-light': {
    label: 'Spring Light',
    description: 'Nhẹ nhàng dịu dàng như đào nhạt, vàng bơ và mint tươi.',
    undertone: 'warm',
    palette: ['#FECBA1', '#FAFAD2', '#98FB98', '#FFB6C1', '#F5DEB3', '#B0E0E6'],
    avoid: ['#1A1A2E', '#16213E', '#0F3460'],
    metallic: 'rose-gold',
    outfitKeywords: {
      casual: ['áo pastel đào', 'quần mint', 'giày nude ấm'],
      office: ['blouse ivory', 'quần cà phê sữa', 'phụ kiện rose gold'],
      party: ['váy blush pink', 'trang sức rose gold', 'túi ánh hồng vàng'],
    },
  },
  'spring-bright': {
    label: 'Spring Bright',
    description: 'Ấm và sặc sỡ như san hô tươi, xanh lá và vàng chanh mùa xuân.',
    undertone: 'warm',
    palette: ['#FF6347', '#FFD700', '#32CD32', '#00CED1', '#FF69B4', '#FF4500'],
    avoid: ['#808080', '#696969', '#A9A9A9'],
    metallic: 'gold',
    outfitKeywords: {
      casual: ['áo xanh lá lime', 'quần trắng', 'giày cam đất'],
      office: ['blazer vàng tươi', 'áo trắng', 'quần kem'],
      party: ['váy coral sặc sỡ', 'trang sức vàng bóng', 'clutch vàng'],
    },
  },
  'spring-clear': {
    label: 'Spring Clear',
    description: 'Trong sáng ấm áp như trắng ngà, aqua ấm và hồng tươi.',
    undertone: 'warm',
    palette: ['#FDFFF5', '#00FFFF', '#FFB6C1', '#FFFF00', '#E6AEFF', '#BFFF00'],
    avoid: ['#556B2F', '#8B4513', '#2F4F4F'],
    metallic: 'gold',
    outfitKeywords: {
      casual: ['áo trắng ngà', 'quần aqua', 'giày trong suốt'],
      office: ['blouse hồng nhạt', 'quần kem ấm', 'phụ kiện vàng nhẹ'],
      party: ['váy ánh kim ấm', 'trang sức vàng mỏng', 'túi ánh vàng nhạt'],
    },
  },

  'summer-cool': {
    label: 'Summer Cool',
    description: 'Lạnh dịu như oải hương, xanh phấn và hồng bụi mùa hè.',
    undertone: 'cool',
    palette: ['#E6CDFF', '#DDA0DD', '#ADD8E6', '#008B8B', '#9370DB', '#FFC0CB'],
    avoid: ['#FF8C00', '#FFD700', '#A0522D'],
    metallic: 'silver',
    outfitKeywords: {
      casual: ['áo oải hương', 'quần xanh nhạt', 'giày bạc'],
      office: ['blazer tím bụi', 'blouse trắng lạnh', 'quần xám lạnh'],
      party: ['váy lavender', 'trang sức bạc nhẹ', 'túi ánh tím bạc'],
    },
  },
  'summer-light': {
    label: 'Summer Light',
    description: 'Nhẹ nhàng lạnh như xanh da trời, hồng phấn và trắng lạnh.',
    undertone: 'cool',
    palette: ['#ADD8E6', '#FFB6C1', '#E6CDFF', '#98FF98', '#FAFAFA', '#F0F8FF'],
    avoid: ['#000080', '#8B0000', '#006400'],
    metallic: 'silver',
    outfitKeywords: {
      casual: ['áo xanh da trời nhạt', 'quần trắng lạnh', 'giày trắng'],
      office: ['blouse trắng lạnh', 'quần xám nhạt', 'phụ kiện bạc nhẹ'],
      party: ['váy hồng phấn', 'trang sức bạc tinh tế', 'túi trắng ánh bạc'],
    },
  },
  'summer-soft': {
    label: 'Summer Soft',
    description: 'Mềm mại lạnh như hồng tím mờ, sage lạnh và xanh bụi.',
    undertone: 'cool',
    palette: ['#C9A8C4', '#A8B87E', '#78A89E', '#C8A8B8', '#87ABCA', '#ABABAB'],
    avoid: ['#FF4500', '#FF8C00', '#FFD700'],
    metallic: 'silver',
    outfitKeywords: {
      casual: ['áo màu tro lạnh', 'quần sage lạnh', 'giày xám nhạt'],
      office: ['vest xám lạnh', 'blouse lavender nhạt', 'quần charcoal nhạt'],
      party: ['váy mauve', 'trang sức bạc mờ', 'túi xám ánh bạc'],
    },
  },
  'summer-muted': {
    label: 'Summer Muted',
    description: 'Trầm mờ lạnh như xám bồ câu, hồng cũ và tím bụi nhạt.',
    undertone: 'cool',
    palette: ['#A8A8A8', '#C4A0A8', '#A0A878', '#788888', '#B8A0A8', '#A8A8C8'],
    avoid: ['#FF0000', '#FF6600', '#FFCC00'],
    metallic: 'silver',
    outfitKeywords: {
      casual: ['áo xám bồ câu', 'quần mauve', 'giày xám'],
      office: ['suit xám lạnh', 'blouse hồng cũ', 'quần tro'],
      party: ['váy periwinkle', 'trang sức bạc xỉn', 'túi xám khói'],
    },
  },
};

module.exports = seasonalPalettes;
